# Generated by Django 3.1.7 on 2021-03-24 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='desciption',
            new_name='description',
        ),
    ]
