# Generated by Django 3.1.7 on 2021-04-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20210329_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='NAME')),
                ('albums', models.ManyToManyField(to='photo.Album')),
            ],
        ),
    ]
