# Generated by Django 3.1 on 2021-03-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210303_2222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lhoice',
            new_name='Choice',
        ),
    ]
