# Generated by Django 3.1.7 on 2021-03-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210321_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modify_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='MODIFY DATE'),
        ),
    ]
