# Generated by Django 3.1.7 on 2021-03-23 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210322_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='desccription',
            new_name='description',
        ),
    ]
